const {
    REACT_APP_LYRIC_API_BASE: LYRIC_API_BASE,
    REACT_APP_CLIENT_ID: CLIENT_ID,
    REACT_APP_CLIENT_SECRET: CLIENT_SECRET,
    REACT_APP_API_KEY: API_KEY,
    REACT_APP_API_BASE: API_BASE
} = process.env;

export {
    LYRIC_API_BASE,
    CLIENT_ID,
    CLIENT_SECRET,
    API_KEY,
    API_BASE
}